In [1]:
import numpy as np

**Уровень 0:**

**Задание 1**

1.   Создайте матрицу 3 на 3, заполненную числами от 1 до 9
2.   Прибавьте к ней матрицу с единицами на диагонале
3.   Умножьте полученную матрицу на вектор (1, 2, 3)
4.   Вычислить транспонированную матрицу от полученной в результате прибавления матр.
5.   Посчитайте обратную матрицу к полученной в результате прибавления матрице





In [4]:
# 1.1
matrix_tel = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_tel

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
# 1.2
mat_1 = matrix_tel + np.eye(3)
mat_1

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [15]:
# 1.3
mat_2 = mat_1 * np.array([1, 2, 3])
mat_2

array([[ 2.,  4.,  9.],
       [ 4., 12., 18.],
       [ 7., 16., 30.]])

In [16]:
# 1.4
mat_1T =  np.transpose(mat_1)
mat_1T

array([[ 2.,  4.,  7.],
       [ 2.,  6.,  8.],
       [ 3.,  6., 10.]])

In [20]:
# 1.5
mat_1_inv = np.linalg.inv(mat_1)
mat_1_inv

array([[-6.00000000e+00, -2.00000000e+00,  3.00000000e+00],
       [-1.00000000e+00,  5.00000000e-01, -2.33146835e-16],
       [ 5.00000000e+00,  1.00000000e+00, -2.00000000e+00]])

In [19]:
# Проверка
mat_1_inv @ mat_1

array([[ 1.00000000e+00,  0.00000000e+00,  3.55271368e-15],
       [-7.77156117e-17,  1.00000000e+00,  1.11022302e-16],
       [ 6.66133815e-16,  0.00000000e+00,  1.00000000e+00]])

**Уровень 1:**

**Задание 2**

Найдите собственные значения и собственные вектора матрицы:

In [21]:
m = np.array([[2, 2],
              [1, 3]])
print(m)

[[2 2]
 [1 3]]


In [44]:
res_m = np.linalg.eig(m)

print(f'Cобственные значения матрицы: {res_m[0]}')

np.transpose(res_m[1])
vec_1 = np.transpose(res_m[1])[0] / np.transpose(res_m[1])[0][-1]
vec_2 = np.transpose(res_m[1])[1] / np.transpose(res_m[1])[1][-1]

print(f'Собственные вектора матрицы:{vec_1} и {vec_2}')

Cобственные значения матрицы: [1. 4.]
Собственные вектора матрицы:[-2.  1.] и [1. 1.]
